# -*- coding: utf-8 -*-
"""case study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyohK-HjBFDYIo0oYLCFGybkBQ-mz3Uy

#1. Bank Account Manager
a.  Simulate a bank account with deposit, withdrawal, and balance enquiry operations

b. Use variables and data types to store account information

c. Implement conditional statements to check for sufficient balancebefore withdrawal

d. Use functions to perform deposit, withdrawal, and balance inquiryoperations.
"""

amount = 50000

def deposit(balance,amount):
  amount = balance+amount
  return amount

def withdrawal(balance,amount):
  if amount <= balance:
     amount = balance-amount
     return amount

  else:
    print('insufficiant fund')
    return amount
def check_balance(amount):
  print('after withdrawal:',amount)


balance = deposit(amount, 500)
print('after deposit:',balance)

balance = withdrawal(balance,1000)
print('after withdrawal:',balance)

check_balance(amount)

"""#2. Weather Data Analyzer
a. Analyze weather data (temperature, humidity, etc.) for a given region


b. Use variables and data types to store weather data


c. Implement conditional statements to determine weather conditions
(sunny, rainy, etc.)


d. Use functions to calculate average temperature and humidity, and
print results
"""

from statistics import mean,median, mode
humidity =[13,19,20,1,6,00]
print('mean:',mean(humidity))
print('median:',median(humidity))
print('mode:',mode(humidity))

"""#4. Word Frequency Counter
Given a paragraph of text, write a function that returns the 3 most
frequently occurring words (ignore case and punctuation).

"""

from collections import Counter

text = input("Enter text: ")
words = text.lower().replace(".", "").replace(",", "").split()

print(Counter(words).most_common(3))

"""#5. FizzBuzz Variant
Print numbers 1 to 50, but replace multiples of 3 with "Fizz", multiples of 5
with "Buzz", multiples of both with "FizzBuzz" — and multiples of 7 with
"Bang".
"""

for i in range(3, 5):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    elif i % 7 == 0:
        print("Bang")
    else:
        print(i)