# -*- coding: utf-8 -*-
"""intermediate assessment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MI4dTBwr0IBGHMovntTlwMSCacZZTSuK

Q1. Write a function that return the range (maximum and minimum) of a given list of numbers
"""

numbers = [13,19,20,00]

def range_value(numbers):
    return max(numbers), min(numbers)

print(range_value([13,19,20,00]))

"""Q2. Write function that returns mean value of a list of numbers"""

def mean(numbers):
    return sum(numbers) / len(numbers)

print(mean([13,19,20,00]))

"""Q3. Write a function that returns the median value of a list of numbers"""

def median(numbers):
    numbers.sort()
    n = len(numbers)
    mid = n // 2

    if n % 2 == 0:
        return (numbers[mid-1] + numbers[mid]) / 2
    return numbers[mid]

print(median([13,19,20,00]))

"""Q4. Write a function to return the mod of a list of numbers, if no mod exists, i should return None. If more than one mod exist, return the mod values as list"""

from collections import Counter

def mode(numbers):
    count = Counter(numbers)
    highest = max(count.values())

    if highest == 1:
        return None

    return [x for x in count if count[x] == highest]

print(mode([4,5,6,7,8,3,2,1]))

"""Q5. Write function to compute a given percentile value (e.g. 90th percentile) of a list of number"""

def percentile(numbers, p):
    numbers.sort()
    index = (p / 100) * (len(numbers) - 1)
    return numbers[round(index)]

print(percentile([63,13,14,15,16,17],10))